Revert "screebo: Add audio beep for ALC1019"
This reverts commit b389d6698c485b57d2990977b94275d66018d3c9.

Reason for revert: compilation error due to undefined FW_CONFIG name.

src/board/rex/screebo.c: In function 'variant_probe_audio_config':
/build/rex/tmp/portage/sys-boot/depthcharge-9999/work/depthcharge-9999/depthcharge/src/base/fw_config.h:27:23: error: 'FW_CONFIG_FIELD_AUDIO_NAME' undeclared (first use in this function); did you mean 'FW_CONFIG_FIELD_MB_CONFIG_NAME'?

Original change's description:
> screebo: Add audio beep for ALC1019
>
> Add max98357 support.
>
> BUG=b:278169268
> BRANCH=none
> TEST=dev beep working on screebo
>
> Change-Id: I23b2e35ca57e5bdeebab025a381e01c16d992fbe
> Signed-off-by: zhourui <zhourui@huaqin.corp-partner.google.com>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/4560425
> Reviewed-by: Kun Liu <liukun11@huaqin.corp-partner.google.com>
> Reviewed-by: YH Lin <yueherngl@chromium.org>

Bug: b:278169268
Change-Id: I000f1a279864fe793ef9fa103f69d4fb357b8eaa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/4572751
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Subrata Banik <subratabanik@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>