drivers/sound/hda_codec: Fix int-to-pointer-cast error Android Bringup: See http://go/android-fw-sync
The fatcat build is failing due to the following error:
src/drivers/sound/hda_codec.c:173:11: error: cast to pointer from integer of
different size [-Werror=int-to-pointer-cast]
  173 |    return (void *)(pci_read_resource(hda_dev, 0) & ~0xf);
      |           ^

BUG=none
TEST=cq
BRANCH=none

(cherry picked from commit 5c91cd9082f114393f17d15d3dfcd24473eff961)

Change-Id: I7485037a371e289c73d1957f2ecde3b927dacaf4
Original-Signed-off-by: Ian Feng <ian_feng@compal.corp-partner.google.com>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6022386
Original-Reviewed-by: Subrata Banik <subratabanik@chromium.org>
Original-Commit-Queue: Subrata Banik <subratabanik@chromium.org>
GitOrigin-RevId: 5c91cd9082f114393f17d15d3dfcd24473eff961
Cr-Build-Id: 8730937884456013105
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730937884456013105
Copybot-Job-Name: android-main-depthcharge-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6030229
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>