mmc: Set a default value for the clock variable
GCC found that the clock variable could be used without being set.  Set
it to 1 which is used by mmc_setup_media() below to initialize to the
lowest valid frequency before we have read any descriptors.

This and will usually end up as 400KHz after the clamping in
mmc_set_clock())

This warning was causing a build failure:
src/drivers/storage/mmc.c:503:8: error: 'clock' may be used
uninitialized in this function [-Werror=maybe-uninitialized]

BUG=none
BRANCH=none
TEST=Build now passes in upstream coreboot

Change-Id: I39013ab05e1f072ae790f853c3e2f845bd780185
Signed-off-by: Martin Roth <martinroth@google.com>
Reviewed-on: https://chromium-review.googlesource.com/457811
Commit-Ready: Martin Roth <martinroth@chromium.org>
Tested-by: Martin Roth <martinroth@chromium.org>
Reviewed-by: Julius Werner <jwerner@chromium.org>