Android Bringup: See http://go/android-fw-sync  arch/x86/boot: Fix int-to-pointer-cast error
The fatcat build is failing due to the following error:

 src/arch/x86/boot.c:107:29: error: cast to pointer from integer of
 different size [-Werror=int-to-pointer-cast]
 107 |      fixup_android_boottime((void *)hdr->ramdisk_image, hdr->ramdisk_size,
     |                             ^

I'm not sure why brya and dedede are not having the same error reported,
but the problem should be fixed by first casting the integer to
uintptr_t.

BUG=none
TEST=cq
BRANCH=none

(cherry picked from commit c8068176f8e5552d5beaed200dae7e6e900512f9)

Change-Id: I62e2d1cd5e60189f0c1940e80a3bf686a1a5f4d2
Original-Signed-off-by: Yu-Ping Wu <yupingso@chromium.org>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/5922583
Original-Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
GitOrigin-RevId: c8068176f8e5552d5beaed200dae7e6e900512f9
Cr-Build-Id: 8734108774850805329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8734108774850805329
Copybot-Job-Name: android-main-fw-nissa-depthcharge-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/5927693
Commit-Queue: Łukasz Majczak <lmajczak@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Łukasz Majczak <lmajczak@google.com>