depthcharge: Fix unit tests with GCC 15
GCC 15.2 turns some diagnostics into errors and also exposes a latent
test bug during unit test phase (the last one):

  src/drivers/input/mkbp/mkbp.c:56:25: error: 'events' may be used
  uninitialized [-Werror=maybe-uninitialized]

  tests/vboot/ui/log-test.c:103:28: error: 'ui_log_set_anchors' reading
  8 bytes from a region of size 0 [-Werror=stringop-overread]

  test_android_misc_reset_oem_cmd: difference at offset 5/6/7

The first one is trivial, just initialize events when declaring.

In log-test.c, the anchors[] array is always empty, which triggers the
new -Wstringop-overread check. Pass NULL instead. An alternative would
be to also drop the assert entirely.

For android_misc-test.c, android_misc_reset_oem_cmd() never wrote the
reserved byte, so the test only passed when stack garbage at cmd[5]
happened to be 0xfe (the poison value setup_test_cmd() uses). GCC 15
broke that coincidence. Initialize cmd->reserved = 0 in the reset
function so it fully defines the bytes the test compares, and clear
expected_cmd.reserved in the test before computing the checksum.

BRANCH=main
BUG=b:493144630
TEST=FEATURES=test emerge-rauru depthcharge with GCC 15.2

Change-Id: I895c2cefdccaab46e2cbf2be075ac15610398ba3
Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/7800875
Reviewed-by: Yidi Lin <yidilin@google.com>
Tested-by: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: Bob Haarman <inglorion@chromium.org>
Commit-Queue: Adrian Ratiu <adrian.ratiu@collabora.corp-partner.google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>